export const PRODUCTIVE_ICON = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKRJREFUWEftl8sSgCAIReX/P9oWaZEBPlJhJlqX93hqkguh94ohio9AgJ4l226uhXKJDTAywGhwCSSA8ACzwjMMA0EDzA4XIN4Aq8IZiCfA6nAC4gbYFV5AGAHYvXtk4TTwbwCt3afXAGr6HcANuIHLgP8JTRjQgEgzopF5IJ/Puw4mNCEbG0pXmyC6gdFiMtvEUDXD/W704/xcTqnWW4NpCMXLHrLoQBEUHWI8AAAAAElFTkSuQmCC"
export const UNPRODUCTIVE_ICON = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKNJREFUWEftl+sOgCAIRuH9H9q2Nh0Z4CUVtuh3eY5fNz6EwSMBJO0SBMCRJbtObkElYI+MKjALroU0EVFgFTzLSBKswGq4JvES2AWXJB4Cu+GcRBE4Ba8lfAic3j1N4U7g3wJWuy+3IQQigUjAPIH4ErpIwEIiz4g+5oH8Yzj1RtAJ2ddQujsJrhv4LCark5iqZrTfzT6cn8sp13pbMj1Quu4F0uBAEczCnXkAAAAASUVORK5CYIIA"
export const PRODUCTIVE_DESCRIPTION = "The user is being productive";
export const UNPRODUCTIVE_DESCRIPTION = "The user is not productive";

export const GREEN = "#34d399";
export const RED = "#f87171";
export const GREEN_SECONDARY = "#86efac";
export const RED_SECONDARY = "#fca5a5";

export const ANALYSIS_DELAY = 300000;
export const SNAPSHOT_DELAY = 10000;
export const SNAPSHOT_STORAGE_LIMIT = 100;